version: 0.1.{build}
branches:
  only:
    - master
    - appveyor
skip_branch_with_pr: true
os: Visual Studio 2017
build_script:
  - ps: dotnet pack -c Release -o "$(pwd)/artifacts/" "-p:Version=${env:APPVEYOR_BUILD_VERSION}"
test: off
artifacts:
  - path: '**\*.nupkg'
    name: Packages
    type: NuGetPackages
deploy:
  - provider: NuGet
    name: myget
    artifact: Packages
    server: https://www.myget.org/F/natemcmaster/api/v2/package
    symbol_server: https://www.myget.org/F/natemcmaster/api/v2/package
    on:
      branch: master
    api_key:
      secure: KF1yGk4IHJyyfiHfFSCxJ+p5iZX+KPfCTnCihjD5iIZjasTS1lHeilpbaon4wvcM
  - provider: GitHub
    tag: v$(appveyor_build_version)
    auth_token:
      secure: 7gza5cyC0Fwp5LcFPz9dGMcHXP2jxbrnu7er9R/HkdvnhzGJVADvOtfYO7+Vow5p
    artifact: Packages
    draft: true
    prerelease: false
    on:
      branch: master                 # release from master branch only
